from __future__ import annotations

from typing import Dict

# Curated simplification resource for news text.
# mode="replace" => safe enough for direct substitution when contextual checks pass
# mode="gloss"   => keep original wording in the text, but allow glossary help
LEXICON: Dict[str, Dict[str, str]] = {
    "approximately": {"replacement": "about", "gloss": "approximately = about", "mode": "replace"},
    "additional": {"replacement": "more", "gloss": "additional = more", "mode": "replace"},
    "announced": {"replacement": "said", "gloss": "announced = said publicly", "mode": "replace"},
    "attempted": {"replacement": "tried", "gloss": "attempted = tried", "mode": "replace"},
    "commence": {"replacement": "start", "gloss": "commence = start", "mode": "replace"},
    "commenced": {"replacement": "started", "gloss": "commenced = started", "mode": "replace"},
    "conclude": {"replacement": "end", "gloss": "conclude = end", "mode": "replace"},
    "concluded": {"replacement": "ended", "gloss": "concluded = ended", "mode": "replace"},
    "demonstrate": {"replacement": "show", "gloss": "demonstrate = show", "mode": "replace"},
    "demonstrated": {"replacement": "showed", "gloss": "demonstrated = showed", "mode": "replace"},
    "determine": {"replacement": "find", "gloss": "determine = find out", "mode": "replace"},
    "determined": {"replacement": "found", "gloss": "determined = found", "mode": "replace"},
    "disclose": {"replacement": "reveal", "gloss": "disclose = reveal", "mode": "replace"},
    "disclosed": {"replacement": "revealed", "gloss": "disclosed = revealed", "mode": "replace"},
    "enable": {"replacement": "allow", "gloss": "enable = allow", "mode": "replace"},
    "enabled": {"replacement": "allowed", "gloss": "enabled = allowed", "mode": "replace"},
    "encountered": {"replacement": "met", "gloss": "encountered = met or came across", "mode": "replace"},
    "ensure": {"replacement": "make sure", "gloss": "ensure = make sure", "mode": "replace"},
    "estimated": {"replacement": "estimated", "gloss": "estimated = roughly calculated", "mode": "gloss"},
    "examine": {"replacement": "look at", "gloss": "examine = look at closely", "mode": "replace"},
    "examined": {"replacement": "looked at", "gloss": "examined = looked at closely", "mode": "replace"},
    "indicate": {"replacement": "show", "gloss": "indicate = show", "mode": "replace"},
    "indicated": {"replacement": "showed", "gloss": "indicated = showed", "mode": "replace"},
    "individuals": {"replacement": "people", "gloss": "individuals = people", "mode": "replace"},
    "located": {"replacement": "found", "gloss": "located = found in a place", "mode": "replace"},
    "maintain": {"replacement": "keep", "gloss": "maintain = keep", "mode": "replace"},
    "maintained": {"replacement": "kept", "gloss": "maintained = kept", "mode": "replace"},
    "obtain": {"replacement": "get", "gloss": "obtain = get", "mode": "replace"},
    "obtained": {"replacement": "got", "gloss": "obtained = got", "mode": "replace"},
    "purchase": {"replacement": "buy", "gloss": "purchase = buy", "mode": "replace"},
    "purchased": {"replacement": "bought", "gloss": "purchased = bought", "mode": "replace"},
    "request": {"replacement": "ask for", "gloss": "request = ask for", "mode": "replace"},
    "requested": {"replacement": "asked for", "gloss": "requested = asked for", "mode": "replace"},
    "reside": {"replacement": "live", "gloss": "reside = live", "mode": "replace"},
    "residents": {"replacement": "people", "gloss": "residents = people who live there", "mode": "replace"},
    "sufficient": {"replacement": "enough", "gloss": "sufficient = enough", "mode": "replace"},
    "terminate": {"replacement": "end", "gloss": "terminate = end", "mode": "replace"},
    "terminated": {"replacement": "ended", "gloss": "terminated = ended", "mode": "replace"},
    "utilize": {"replacement": "use", "gloss": "utilize = use", "mode": "replace"},
    "utilized": {"replacement": "used", "gloss": "utilized = used", "mode": "replace"},
    "verify": {"replacement": "check", "gloss": "verify = check", "mode": "replace"},
    "verified": {"replacement": "checked", "gloss": "verified = checked", "mode": "replace"},

    "assistance": {"replacement": "help", "gloss": "assistance = help", "mode": "replace"},
    "benefit": {"replacement": "help", "gloss": "benefit = help or advantage", "mode": "gloss"},
    "damage": {"replacement": "damage", "gloss": "damage = harm done", "mode": "gloss"},
    "debris": {"replacement": "debris", "gloss": "debris = broken pieces left behind", "mode": "gloss"},
    "detention": {"replacement": "detention", "gloss": "detention = being held by authorities", "mode": "gloss"},
    "evidence": {"replacement": "evidence", "gloss": "evidence = facts or items that help prove something", "mode": "gloss"},
    "facility": {"replacement": "building", "gloss": "facility = building or place for a purpose", "mode": "replace"},
    "facilities": {"replacement": "buildings", "gloss": "facilities = buildings or places", "mode": "replace"},
    "findings": {"replacement": "results", "gloss": "findings = results", "mode": "replace"},
    "harm": {"replacement": "harm", "gloss": "harm = injury or damage", "mode": "gloss"},
    "injuries": {"replacement": "injuries", "gloss": "injuries = physical harm", "mode": "gloss"},
    "injury": {"replacement": "injury", "gloss": "injury = physical harm", "mode": "gloss"},
    "requirement": {"replacement": "need", "gloss": "requirement = something needed", "mode": "replace"},
    "requirements": {"replacement": "needs", "gloss": "requirements = things needed", "mode": "replace"},
    "victims": {"replacement": "victims", "gloss": "victims = people harmed", "mode": "gloss"},

    "currently": {"replacement": "now", "gloss": "currently = now", "mode": "replace"},
    "previously": {"replacement": "before", "gloss": "previously = before now", "mode": "replace"},
    "subsequently": {"replacement": "later", "gloss": "subsequently = later", "mode": "replace"},
    "annually": {"replacement": "every year", "gloss": "annually = every year", "mode": "replace"},
    "monthly": {"replacement": "every month", "gloss": "monthly = every month", "mode": "replace"},
    "weekly": {"replacement": "every week", "gloss": "weekly = every week", "mode": "replace"},
    "temporary": {"replacement": "short-term", "gloss": "temporary = for a short time", "mode": "replace"},
    "permanent": {"replacement": "lasting", "gloss": "permanent = lasting", "mode": "replace"},

    "children": {"replacement": "children", "gloss": "children = young people", "mode": "gloss"},
    "elderly": {"replacement": "older people", "gloss": "elderly = older people", "mode": "replace"},
    "families": {"replacement": "families", "gloss": "families = groups of related people", "mode": "gloss"},
    "juvenile": {"replacement": "young", "gloss": "juvenile = young", "mode": "replace"},
    "residents": {"replacement": "people", "gloss": "residents = people who live there", "mode": "replace"},

    "attorney": {"replacement": "lawyer", "gloss": "attorney = lawyer", "mode": "replace"},
    "lawsuit": {"replacement": "lawsuit", "gloss": "lawsuit = case brought to court", "mode": "gloss"},
    "prosecutor": {"replacement": "prosecutor", "gloss": "prosecutor = lawyer trying to prove a crime in court", "mode": "gloss"},
    "prosecutors": {"replacement": "prosecutors", "gloss": "prosecutors = lawyers trying to prove a crime in court", "mode": "gloss"},
    "sentence": {"replacement": "sentence", "gloss": "sentence = a court punishment", "mode": "gloss"},
    "testimony": {"replacement": "testimony", "gloss": "testimony = statement given in court", "mode": "gloss"},
    "verdict": {"replacement": "decision", "gloss": "verdict = court decision", "mode": "replace"},
    "witnesses": {"replacement": "witnesses", "gloss": "witnesses = people who saw something happen", "mode": "gloss"},

    "campaign": {"replacement": "effort", "gloss": "campaign = organized effort", "mode": "replace"},
    "conflict": {"replacement": "fighting", "gloss": "conflict = serious disagreement or fighting", "mode": "replace"},
    "controversy": {"replacement": "dispute", "gloss": "controversy = public disagreement", "mode": "replace"},
    "criticized": {"replacement": "criticized", "gloss": "criticized = said something was wrong", "mode": "gloss"},
    "democracy": {"replacement": "democracy", "gloss": "democracy = system where people choose leaders by voting", "mode": "gloss"},
    "diplomatic": {"replacement": "diplomatic", "gloss": "diplomatic = related to relations between countries", "mode": "gloss"},
    "government": {"replacement": "government", "gloss": "government = group that runs a country", "mode": "gloss"},
    "governor": {"replacement": "state leader", "gloss": "governor = elected head of a state", "mode": "replace"},
    "legislation": {"replacement": "law", "gloss": "legislation = law or proposed law", "mode": "replace"},
    "minister": {"replacement": "minister", "gloss": "minister = senior government official", "mode": "gloss"},
    "opposition": {"replacement": "opposition", "gloss": "opposition = political group against those in power", "mode": "gloss"},
    "parliament": {"replacement": "parliament", "gloss": "parliament = national lawmaking body", "mode": "gloss"},
    "policy": {"replacement": "plan", "gloss": "policy = official plan", "mode": "replace"},
    "president": {"replacement": "president", "gloss": "president = elected national leader in some countries", "mode": "gloss"},
    "security": {"replacement": "safety", "gloss": "security = safety and protection", "mode": "replace"},
    "spokesman": {"replacement": "spokesperson", "gloss": "spokesman = person speaking for a group", "mode": "replace"},
    "spokeswoman": {"replacement": "spokesperson", "gloss": "spokeswoman = person speaking for a group", "mode": "replace"},
    "statement": {"replacement": "statement", "gloss": "statement = official spoken or written message", "mode": "gloss"},
    "troops": {"replacement": "soldiers", "gloss": "troops = soldiers", "mode": "replace"},
    "violence": {"replacement": "violent attacks", "gloss": "violence = use of physical force to hurt", "mode": "replace"},

    "economy": {"replacement": "economy", "gloss": "economy = system of money, jobs, and business", "mode": "gloss"},
    "economic": {"replacement": "money-related", "gloss": "economic = related to money and jobs", "mode": "replace"},
    "financial": {"replacement": "money-related", "gloss": "financial = related to money", "mode": "replace"},
    "inflation": {"replacement": "inflation", "gloss": "inflation = prices rising over time", "mode": "gloss"},
    "investment": {"replacement": "investment", "gloss": "investment = money put in to gain more later", "mode": "gloss"},
    "investors": {"replacement": "investors", "gloss": "investors = people or groups who put money into something", "mode": "gloss"},
    "recession": {"replacement": "economic slowdown", "gloss": "recession = period when business gets weaker", "mode": "replace"},
    "revenue": {"replacement": "income", "gloss": "revenue = money a company or government receives", "mode": "replace"},
    "shares": {"replacement": "shares", "gloss": "shares = small ownership units in a company", "mode": "gloss"},
    "stocks": {"replacement": "stocks", "gloss": "stocks = shares in a company", "mode": "gloss"},

    "device": {"replacement": "device", "gloss": "device = piece of equipment", "mode": "gloss"},
    "technology": {"replacement": "technology", "gloss": "technology = tools and systems made using science", "mode": "gloss"},
    "vaccine": {"replacement": "vaccine", "gloss": "vaccine = medicine that helps prevent disease", "mode": "gloss"},
    "virus": {"replacement": "virus", "gloss": "virus = tiny germ that causes disease", "mode": "gloss"},

    "authorities": {"replacement": "officials", "gloss": "authorities = officials in charge", "mode": "replace"},
    "congress": {"replacement": "lawmakers", "gloss": "Congress = national lawmakers", "mode": "replace"},
    "department": {"replacement": "office", "gloss": "department = government office or part", "mode": "replace"},
    "director": {"replacement": "head", "gloss": "director = person in charge", "mode": "replace"},
    "officials": {"replacement": "officials", "gloss": "officials = people in charge", "mode": "gloss"},
    "organization": {"replacement": "group", "gloss": "organization = group with a shared purpose", "mode": "replace"},
    "organizations": {"replacement": "groups", "gloss": "organizations = groups with a shared purpose", "mode": "replace"},
    "representative": {"replacement": "representative", "gloss": "representative = person speaking or acting for others", "mode": "gloss"},

    "difficult": {"replacement": "hard", "gloss": "difficult = hard", "mode": "replace"},
    "significant": {"replacement": "major", "gloss": "significant = important or large", "mode": "replace"},
    "significantly": {"replacement": "a lot", "gloss": "significantly = by a lot", "mode": "replace"},
    "numerous": {"replacement": "many", "gloss": "numerous = many", "mode": "replace"},
    "various": {"replacement": "different", "gloss": "various = different", "mode": "replace"},
    "critical": {"replacement": "very important", "gloss": "critical = extremely important", "mode": "replace"},
    "major": {"replacement": "major", "gloss": "major = very important or large", "mode": "gloss"},

    "investigation": {"replacement": "investigation", "gloss": "investigation = careful official check", "mode": "gloss"},
    "investigations": {"replacement": "investigations", "gloss": "investigations = careful official checks", "mode": "gloss"},
    "identified": {"replacement": "named", "gloss": "identified = named or recognized", "mode": "replace"},
    "suspect": {"replacement": "suspect", "gloss": "suspect = person thought to be involved in a crime", "mode": "gloss"},
    "suspects": {"replacement": "suspects", "gloss": "suspects = people thought to be involved in a crime", "mode": "gloss"},
    "charges": {"replacement": "charges", "gloss": "charges = formal claims of a crime", "mode": "gloss"},
    "accused": {"replacement": "accused", "gloss": "accused = said to have done something wrong", "mode": "gloss"},
    "alleged": {"replacement": "alleged", "gloss": "alleged = claimed but not yet proven", "mode": "gloss"},

    "according": {"replacement": "according", "gloss": "according to = as said by", "mode": "gloss"},
    "meanwhile": {"replacement": "at the same time", "gloss": "meanwhile = at the same time", "mode": "replace"},
    "however": {"replacement": "but", "gloss": "however = but", "mode": "replace"},
    "therefore": {"replacement": "so", "gloss": "therefore = so", "mode": "replace"},
    "although": {"replacement": "though", "gloss": "although = though", "mode": "replace"},
    "because": {"replacement": "because", "gloss": "because = for the reason that", "mode": "gloss"},
    "despite": {"replacement": "despite", "gloss": "despite = even though", "mode": "gloss"},
    "due": {"replacement": "because", "gloss": "due to = because of", "mode": "replace"},
}

PHRASE_REPLACEMENTS = {
    "in order to": "to",
    "at this point": "now",
    "due to": "because of",
}